export const OG_LOGICAL_WIDTH = 1_200;
export const OG_LOGICAL_HEIGHT = 630;
export const OG_DEVICE_PIXEL_RATIO = 2;
export const OG_WIDTH = OG_LOGICAL_WIDTH * OG_DEVICE_PIXEL_RATIO;
export const OG_HEIGHT = OG_LOGICAL_HEIGHT * OG_DEVICE_PIXEL_RATIO;
